/*
# Ambient Traffic Readings — Switch to Real TomTom Traffic Data

## Summary
The `ambient_traffic_readings` table previously stored numbers generated by a
`Math.random()` formula inside the edge function, labeled "simulated-sensor".
This migration reshapes the table to match real data returned by the TomTom
Traffic Flow Segment Data API:

- Drops `vehicle_count`, which had no real equivalent and was fabricated.
- Adds `confidence_pct` (0–100), TomTom's own confidence score for the reading.
- Adds `road_closed` (boolean), from TomTom's `roadClosure` field.
- Changes the default/allowed values for `source` to `tomtom` so it's clear,
  at the schema level, that this is a named real provider rather than a
  simulation.

## Notes
- This does not change RLS: reads stay public, writes stay restricted to the
  service role (used only by the `ambient-traffic` edge function).
*/

ALTER TABLE public.ambient_traffic_readings
  DROP COLUMN IF EXISTS vehicle_count;

ALTER TABLE public.ambient_traffic_readings
  ADD COLUMN IF NOT EXISTS confidence_pct int NOT NULL DEFAULT 100
    CHECK (confidence_pct >= 0 AND confidence_pct <= 100);

ALTER TABLE public.ambient_traffic_readings
  ADD COLUMN IF NOT EXISTS road_closed boolean NOT NULL DEFAULT false;

ALTER TABLE public.ambient_traffic_readings
  ALTER COLUMN source SET DEFAULT 'tomtom';

-- Backfill any existing rows so the label no longer claims to be simulated
UPDATE public.ambient_traffic_readings SET source = 'tomtom' WHERE source = 'simulated-sensor';
